/**
 * Type definitions barrel export for Enspira
 * Import from '@/types' for all shared types
 */

// Configuration types
export type {
  ServerEndpoints,
  ExternalScraperConfig,
  ServerConfig,
  BraveConfig,
  MilvusCollections,
  MilvusConfig,
  TwitchScopes,
  TwitchConfig,
  ModelType,
  ApiKeyType,
  EmbeddingType,
  BaseModelConfig,
  LLMModelConfig,
  SummaryModelConfig,
  ChatModelConfig,
  EmbeddingModelConfig,
  RerankModelConfig,
  ClassifierModelConfig,
  ModeratorModelConfig,
  ModelsConfig,
  ChatSamplerConfig,
  ToolSamplerConfig,
  SamplersConfig,
  TTSEndpoints,
  TTSProviderConfig,
  TTSPreference,
  FunFactsConfig,
  ExtensionsAppConfig,
  AppConfig,
  ConfigPath,
} from './config.types.js';

// User types
export type {
  AlternateSpellMapping,
  AlternateSpell,
  TwitchTokenData,
  StreamerTwitchTokenData,
  TwitchTokens,
  TwitchSubscription,
  TwitchSubscriptionStatus,
  UserSocials,
  TTSEqPreference,
  StreamStatus,
  CurrentGame,
  UserCommand,
  AuxBot,
  User,
  CreateUserInput,
  UpdateUserInput,
  CachedUser,
  UserLookupResult,
  // Chat message types
  ChatMessageMetadata,
  DbChatMessage,
  StoreChatMessageInput,
  StoreChatMessageResult,
  FormattedChatMessage,
  // Database cache types
  UserCacheEntry,
  DatabaseHealthResult,
  CachingOptions,
  RelevantContextOptions,
} from './user.types.js';

// Twitch types
export type {
  TwitchEventType,
  EventSubMessageType,
  EventSubPayload,
  EventSubSubscription,
  EventSubTransport,
  FollowEvent,
  SubscribeEvent,
  SubscriptionTier,
  SubscriptionMessageEvent,
  SubscriptionMessage,
  Emote,
  GiftSubscriptionEvent,
  CheerEvent,
  RaidEvent,
  ChannelPointsRedemptionEvent,
  ChannelPointsReward,
  HypeTrainEvent,
  HypeTrainContribution,
  StreamOnlineEvent,
  StreamOfflineEvent,
  BanEvent,
  PollChoice,
  PollEvent,
  PredictionOutcome,
  TopPredictor,
  PredictionEvent,
  ShoutoutCreateEvent,
  ShoutoutReceiveEvent,
  TwitchChatMessage,
  TwitchUser,
  TwitchStream,
  TwitchGame,
  EventSubRegistrationResult,
  EventSubHealthResult,
} from './twitch.types.js';

// AI types
export type {
  MessageRole,
  ChatMessage,
  ContentPart,
  TextContentPart,
  ImageContentPart,
  ToolDefinition,
  FunctionDefinition,
  JSONSchema,
  JSONSchemaProperty,
  ToolCall,
  ChatCompletionRequest,
  ToolChoice,
  ResponseFormat,
  ChatCompletionResponse,
  ChatCompletionChoice,
  FinishReason,
  LogProbs,
  LogProbContent,
  TopLogProb,
  CompletionUsage,
  ChatCompletionChunk,
  ChatCompletionChunkChoice,
  EmbeddingRequest,
  EmbeddingResponse,
  EmbeddingData,
  ModerationRequest,
  ModerationResponse,
  ModerationResult,
  ModerationCategories,
  ModerationCategoryScores,
  RAGContext,
  RAGQueryResult,
  VectorSearchParams,
  VectorSearchResult,
  ExpressionType,
  ParsedExpression,
  ExpressionParseResult,
  ChatRequestInput,
  ChatRequestOutput,
  EventRequestInput,
  VoiceRequestInput,
  RerankRequest,
  RerankResult,
  RerankResponse,
  ClassificationRequest,
  ClassificationResult,
  ClassificationResponse,
  // Web RAG types
  RagError,
  SearchInferenceSuccess,
  SearchInferenceFailure,
  SearchInferenceResult,
  WebUrl,
  RerankItem,
  ContextItem,
  EmotionResult,
  // Location & Weather types
  GeoLocationResponse,
  LocationData,
  WeatherCurrent,
  WeatherResponse,
  // Auth types
  AuthCheckResult,
  // LLM Request Body types
  ChatPromptData,
  BaseLLMRequestBody,
  ChatSamplerValues,
  ToolSamplerValues,
  QueryResponseSchema,
  ModerationResponseSchema,
  SummaryResponseSchema,
  ChainOfThoughtResponseSchema,
  // Expression Parser types
  ParsedExpressionTag,
  ExpressionParseOutput,
  TimedExpression,
  AudioDurationOptions,
  ExpressionProcessingOptions,
  ExpressionDebugInfo,
  ExpressionProcessingResult,
  ExpressionCacheStats,
  // LLM Client types (Phase 6)
  ModelConfig,
  ToolCompletionResult,
  ChatCompletionResult,
  CoTCompletionResult,
  // Prompt Builder types (Phase 6)
  SocialMediaReplacements,
  PromptFileContents,
  TemplateReplacements,
  ContextPromptData,
  StructuredPromptData,
  // Message Utils types (Phase 6)
  TTSFixResult,
  ModerationCacheEntry,
  PromptHelperCacheStats,
  // Chat Handler types (Phase 7)
  ChatData,
  ChatEmote,
  NormalizedChatMessage,
  RateLimitEntry,
  ResponseCacheEntry,
  ChatCacheStats,
  TwitchChatResponse,
  ChatHandlerResponse,
  ChatHandlerStats,
  MemoryPressureReliefResult,
  FirstTimeChatterEventData,
  EventSubMessageData,
  // Milvus Vector DB types (Phase 8)
  MilvusCollectionType,
  MilvusFieldDefinition,
  MilvusIndexParams,
  MilvusCollectionSchema,
  CollectionLoadStatus,
  QueryCacheEntry,
  VectorInsertData,
  PendingVectorBatch,
  MilvusSearchOptions,
  OptimizedSearchParams,
  MilvusSearchResponse,
  MilvusSearchResult,
  MilvusUserInfo,
  // Embedding types (Phase 8)
  EmbeddingApiConfig,
  EmbeddingResult,
  // RAG Context types (Phase 8)
  WebSearchResultItem,
  SummaryResult,
  SearchInferenceParams,
  DocumentComparisonResult,
  DocumentUpsertData,
  // AI Engine types (Phase 8)
  UserExpressionsEntry,
  PromptContextData,
  ContextualResponse,
  AIChatResponse,
  ExpressionEnhancedResponse,
  // Response Generator types (Phase 8)
  VoiceResponseResult,
  FishTTSParameters,
  EventResponseResult,
  MilvusHealthResult,
  CollectionHealthStatus,
  EndpointCheckResult,
  FallbackResponseType,
  // Cache Statistics types (Phase 8)
  QueryCacheStats,
  CollectionLoadStats,
  PendingVectorsStats,
  AIEngineCacheStats,
} from './ai.types.js';

// Extension types
export type {
  ExtensionPermission,
  ExtensionManifest,
  ExtensionConfigSchema,
  ExtensionConfigProperty,
  ExtensionDependency,
  EnspiraEventType,
  EnspiraEventSource,
  EnspiraEventUser,
  EnspiraEventMeta,
  EnspiraEvent,
  EnspiraResponse,
  ExtensionStorage,
  Unsubscribe,
  EventHandler,
  EventBusClient,
  ReadonlyConfig,
  ExtensionContext,
  Extension,
  ExtensionState,
  LoadedExtension,
  MiddlewareHandler,
  ResponseMiddlewareHandler,
  EventSubscription,
  EventBusStats,
  ExtensionLoadOptions,
  ExtensionLoadResult,
  ExtensionRegistryStats,
  WorkerMessageType,
  WorkerMessage,
  WorkerInitMessage,
  WorkerEventMessage,
  ExtensionsConfig,
  DefineExtensionConfig,
} from './extension.types.js';

// Server types (Phase 11)
export type {
  ServerOptions,
  ConnectionLimits,
  RateLimitData,
  ModelInfo,
  WebSocketMessageType,
  WebSocketMessage,
  OutgoingWebSocketMessage,
  DisplayText,
  WebSocketActions,
  ServerInfo,
  ConnectionStats,
  EventListenerEntry,
  SendMessageResult,
  ConnectionValidation,
  WebSocketStatusResponse,
  ConnectionInfo,
  MemoryInfo,
  SystemInfo,
  LLMStatuses,
  PreflightResult,
  InitializeResult,
  AuthResult,
  AlternateSpelling,
  EmotionType,
  EmotionKeywords,
  ExpressionMapping,
} from './server.types.js';
